# -*- coding: utf-8 -*-
"""VIT_AI_BOT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nScr0yPqSIODppNrd4bBOhwkAtrLvHJ6
"""

import requests as requests
import random

url="https://api.telegram.org/bot1100620001:AAFsYCPiVFRuF7Io2_QtDFV5GT3Clt1MLoY/"

def get_chat_id(update):
    chat_id = update['message']["chat"]["id"]
    return chat_id

def get_message_text(update):
    message_text = update["message"]["text"]
    return message_text

def last_update(req):
    response = requests.get(req + "getUpdates")
    response = response.json()
    result = response["result"]
    total_updates = len(result) - 1
    return result[total_updates]

def send_message(chat_id, message_text):
    params = {"chat_id": chat_id, "text": message_text}
    response = requests.post(url + "sendMessage", data=params)
    return response

pairs = [
    [
        r"my name is (.*)",
        ["Hello %1, How are you today ?",]
    ],
    [
        r"(.*)help(.*) ",
        ["I can help you ",]
    ],
     [
        r"(.*) your name ?",
        ["My name is VIT_AI_bot, I'm a chatbot for VIT",]
    ],
    [
        r"how are you ?",
        ["I'm doing very well\nHow about You ?",]
    ],
    [
        r"sorry (.*)",
        ["Its alright","Its OK, never mind that",]
    ],
    [
        r"i'm (.*) doing good",
        ["Nice to hear that","Alright, great !",]
    ],
    [
        r"(hi|hey|hello|hola|holla)(.*)",
        ["Hello", "Hey there",]
    ],
    [
        r"what (.*) want ?",
        ["Make me an offer I can't refuse",]
        
    ],
    [
        r"(.*) created ?",
        ["randerson112358 created me using Python's NLTK library ","top secret ;)",]
    ],
    [
        r"(.*) (location|city) ?",
        ['Tokyo, Japan',]
    ],
    [
        r"how is the weather in (.*)?",
        ["Weather in %1 is amazing like always","It's hot here in %1","It's chilli here in %1", "In %1 there is a 50% chance of rain",]
    ],
    [
        r"i work (in|at) (.*)?",
        ["%1 is an amazing company, I have heard about it.",]
    ],
[
        r"(.*)raining in (.*)",
        ["No rain in the past 4 days here in %2","In %2 there is a 50% chance of rain",]
    ],
    [
        r"is it (.*) in (.*)",
        ["No its not %1 in %2","It could be", "Yes its %1 in %2"]
    ],
    [
        r"how (.*) health (.*)",
        ["Health is very important, but I am a computer, so I don't need to worry about my health ",]
    ],
    [
        r"(.*)(sports|game|sport)(.*)",
        ["I'm a very big fan of Basketball",]
    ],
    [
        r"who (.*) sportsperson ?",
        ["Messy","LeBron", "D-Wade"]
],
    [
        r"who (.*) (moviestar|actor|actress)?",
        ["Zendaya"]
],
    [
        r"quit",
        ["Bye for now. See you soon :) ","It was nice talking to you. See you soon :)"]
],
]

def main():
    update_id = last_update(url)["update_id"]
    while True:
        update = last_update(url)
        if update_id == update["update_id"]:
            if get_message_text(update).lower() == "hi" or get_message_text(update).lower() == "hello":
                send_message(get_chat_id(update), 'Hello Welcome to our VIT!How can we help you?')
            if get_message_text(update) == "I want to know about VIT admission procedure" or get_message_text(update) == "admission procedure":
                send_message(get_chat_id(update), 'Yes sure!To know more about VIT admission procedure please visit : https://vit.ac.in/admissions/overview')
            if get_message_text(update) == "I want to know about VIT academics" or get_message_text(update) == "academics":
                send_message(get_chat_id(update), 'Yes sure!To know more about VIT academics : https://vit.ac.in/academics/home')
            if get_message_text(update) == "I want to know about VIT Placements" or get_message_text(update)== "Placements":
                send_message(get_chat_id(update), 'Yes sure!To know more about VIT Placements : https://vit.ac.in/placements/overview')
            if get_message_text(update) == "I want to know about VIT campus life" or get_message_text(update) == " campus life":
              send_message(get_chat_id(update), 'Yes sure!To know more about VIT campus life : https://vit.ac.in/campuslife/overview')
            if get_message_text(update) == "What are the programs offered?" or get_message_text(update) == "programs offered?":
              send_message(get_chat_id(update), 'Yes sure!To know more about programs offered  : https://vit.ac.in/programmes-offered-2019-20')
            if get_message_text(update) == "I want to know what is ffcs? " or get_message_text(update) == "FFCS ":
                send_message(get_chat_id(update), 'Yes sure!To know more about ffcs  : https://vit.ac.in/academics/ffcs')
            if get_message_text(update) == "I want to know about VIT transcript " or get_message_text(update) == "transcripts ":
                send_message(get_chat_id(update), 'Yes sure!To know more about transcripts  : https://vit.ac.in/about-vit')
            if get_message_text(update) == "I want to know about transcripts " or get_message_text(update) == "transcript ":
                send_message(get_chat_id(update), 'Yes sure!To know more about VIT  : https://vit.ac.in/academics/transcripts')
            if get_message_text(update) == "I want to know about schools in VIT " or get_message_text(update) == "schools in college ":
                send_message(get_chat_id(update), 'Yes sure!To know more about schools in VIT  : https://vit.ac.in/schools')
            if get_message_text(update) == "I want to know about VIT library " or get_message_text(update) == "VIT library ":
                send_message(get_chat_id(update), 'Yes sure!To know more about VIT library  : https://vit.ac.in/academics/library')
            if get_message_text(update) == "I want to know about VIT academic centers " or get_message_text(update) == "VIT Academic centers":
                send_message(get_chat_id(update), 'Yes sure!To know more about VIT academic centers  : https://vit.ac.in/academics/centers')
            if get_message_text(update) == "I want to know about Program offered this year " or get_message_text(update) == "Program offered this year":
                send_message(get_chat_id(update), 'Yes sure!To know more about Program offered this year  : https://vit.ac.in/admissions/programmes-offered')
            if get_message_text(update) == "I want to know about VIT UG admissions " or get_message_text(update) == "VIT UG admissions ":
                send_message(get_chat_id(update), 'Yes sure!To know more about VIT UG admissions  : https://vit.ac.in/all-courses/ug')
            if get_message_text(update) == "I want to know about VIT PG admissions " or get_message_text(update) == "VIT PG admissions":
               send_message(get_chat_id(update), 'Yes sure!To know more about VIT PG admissions  : https://vit.ac.in/all-courses/pg')
            if get_message_text(update) == "I want to know about VIT Research" or get_message_text(update) == "VIT Research ":
               send_message(get_chat_id(update), 'Yes sure!To know more about VIT Research : https://vit.ac.in/admissions/research')
            if get_message_text(update) == "I want to know about VIT International admissions" or get_message_text(update) == "VIT International admissions  ":
                send_message(get_chat_id(update), 'Yes sure!To know more about  VIT International admissions  :https://vit.ac.in/admissions/international/overview')
            if get_message_text(update) == "I want to know about VITEEE 2020 " or get_message_text(update) == " VITEEE 2020 ":
                send_message(get_chat_id(update), 'Yes sure!To know more about  VITEEE 2020  : https://viteee.vit.ac.in/?utm_source=VIT&utm_campaign=viteee2020')
            if get_message_text(update) == "I want to know about VIT Superdream offer " or get_message_text(update) == " VIT Superdream offer ":
                send_message(get_chat_id(update), 'Yes sure!To know more about  VIT Superdream offer : https://vit.ac.in/placements/Superdreamoffers')
            if get_message_text(update) == "I want to know about VIT Dream offer " or get_message_text(update) == " VIT Dream offer":
                send_message(get_chat_id(update), 'Yes sure!To know more about  VIT Dream offer  : https://vit.ac.in/placements/dreamoffers')
            if get_message_text(update) == "I want to know about VIT Internships " or get_message_text(update) == " VIT Internships ":
                send_message(get_chat_id(update), 'Yes sure!To know more about  VIT Internships  : https://vit.ac.in/placements/internship')
            if get_message_text(update) == "I want to know about VIT placement statistics " or get_message_text(update) == " VIT placement statistics":
                send_message(get_chat_id(update), 'Yes sure!To know more about  VIT placement statistics  : https://vit.ac.in/placements/statistics')
            if get_message_text(update) == "I want to know about VIT placement records " or get_message_text(update) == " VIT placement records ":
                send_message(get_chat_id(update), 'Yes sure!To know more about  VIT placement records : https://vit.ac.in/placements/placement-records')
            if get_message_text(update) == "I want to know about VIT PAT office" or get_message_text(update) == " VIT PAT office":
                send_message(get_chat_id(update), 'Yes sure!To know more about  VIT PAT office : https://vit.ac.in/placements/PAT-Office')
            if get_message_text(update) == "I want to know about VIT INTERNATIONAL TRANSFER PROGRAMS (ITP)" or get_message_text(update) == " VIT INTERNATIONAL TRANSFER PROGRAMS (ITP)":
                send_message(get_chat_id(update), 'Yes sure!To know more about  VIT INTERNATIONAL TRANSFER PROGRAMS (ITP)  : https://vit.ac.in/internationalrelations/itp')
            if get_message_text(update) == "I want to know about VIT partner universities" or get_message_text(update) == " VIT partner universities":
                send_message(get_chat_id(update), 'Yes sure!To know more about  VIT partner universities : https://vit.ac.in/internationalrelations/partneruniversities')
            if get_message_text(update) == "I want to know about VIT SAP program " or get_message_text(update) == " VIT SAP program ":
                send_message(get_chat_id(update), 'Yes sure!To know more about  VIT SAP program : https://vit.ac.in/internationalrelations/SAP')
            if get_message_text(update) == "I want to know about VIT International admissions " or get_message_text(update) == " VIT International admissions":
                send_message(get_chat_id(update), 'Yes sure!To know more about  VIT International admissions : https://vit.ac.in/admissions/international/overview')
            if get_message_text(update) == "I want to know about VIT  Academic reserach " or get_message_text(update) == " VIT ACADEMIC Reserach":
                send_message(get_chat_id(update), 'Yes sure!To know more about  VIT  Academic reserach:https://vit.ac.in/research/academic')
            if get_message_text(update) == "I want to know about research centers " or get_message_text(update) == " research centers":
                send_message(get_chat_id(update), 'Yes sure!To know more about  research centers  : https://vit.ac.in/research/academic')
            if get_message_text(update) == "I want to know about VIT vision and mission" or get_message_text(update) == " VIT vision and mission":
                send_message(get_chat_id(update), 'Yes sure!Our vision: Transforming life through excellence in education and research.,Our mission: World class Education: Excellence in education, grounded in ethics and critical thinking, for improvement of life.Cutting edge Research: An innovation ecosystem to extend knowledge and solve critical problems.Impactful People: Happy, accountable, caring and effective workforce and students.Rewarding Co-creations: Active collaboration with national & international industries & universities for productivity and economic development.Service to Society: Service to the region and world through knowledge and compassion.To know more about  VIT vision and mission : https://vit.ac.in/schools')
            if get_message_text(update) == "I want to know about VIT Administrative offices " or get_message_text(update) == " VIT Administrative offices ":
                send_message(get_chat_id(update), 'Yes sure!VIT’s objective of providing quality higher education on par with international standards motivates us to seek and adopt innovative methods and best practices in teaching, learning and research. The campus exudes a cosmopolitan atmosphere with students from all corners of the globe. Experienced and dedicated teachers nurture the students to help them evolve as insightful individuals. VIT’s global standards in teaching and research spur the students in their relentless pursuit of excellence. In fact, it has become the way of life in VIT. The highly motivated students are a source of pride for VIT. A major strength of VIT is its Memoranda of Understanding with prestigious international universities, which provide opportunities for exchange of students and faculty and encourage joint research projects. Students pursuing research projects abroad bring home quality work and esteem for the nation. With steady steps, VIT is continuing its march forward.To know more about  VIT Administrative offices  : https://vit.ac.in/schools')
            if get_message_text(update) == "I want to know about Events in VIT " or get_message_text(update) == " Events in VIT ":
                send_message(get_chat_id(update), 'Yes sure!To know more about  Events in VIT : https://vit.ac.in/all-events')
            if get_message_text(update) == "I want to know about Curent openings for faculty " or get_message_text(update) == "Curent openings for faculty":
                send_message(get_chat_id(update), 'Yes sure!To know more about Curent openings for faculty  : https://careers.vit.ac.in/#top')
            if get_message_text(update) == "I want to know what Carrer in VIT " or get_message_text(update) == "Carrer in VIT":
                send_message(get_chat_id(update), 'Yes sure!To know more about Carrer in VIT  : https://careers.vit.ac.in/overview/')
            if get_message_text(update) == "I want to see gallery" or get_message_text(update) == "like to see Gallery ":
                send_message(get_chat_id(update), 'Yes sure!To see gallery : https://careers.vit.ac.in/overview/#gallery')
            if get_message_text(update) == "I want to Contact VIT?" or get_message_text(update) == "Contact us":
                send_message(get_chat_id(update), 'Yes sure!To contact us  :https://careers.vit.ac.in/overview/#contact')
            if get_message_text(update) == "I want to visit VIT site? " or get_message_text(update) == "VIT Site ":
                send_message(get_chat_id(update), 'Yes sure!VIT Site visit  : https://vit.ac.in/')
            if get_message_text(update) == "I want to know What are the fees for VIT through the management quota?" or get_message_text(update) == "management quota":
                send_message(get_chat_id(update), 'Fee for this admission is being spread between 3.98 lacs to 4.98 lacs depending upon the branch and campus you choose. Since, VIT University is been known for excellent placement it is quite justifiable to pay this amount of fee because to earn more you have to invest more.')
            if get_message_text(update) == "How is life at VIT?" or get_message_text(update) == "life at VIT":
                send_message(get_chat_id(update), 'Academically, VIT is a very good private university. You are never gonna regret your decision if you are coming here to study and learn.There are various clubs and chapters in the University in which you interact with a lot of people including seniors and it is a good experience.')
            if get_message_text(update) == "how are Rules and regulations" or get_message_text(update) == "Rules and regulations":
                send_message(get_chat_id(update), 'The rules and regulations are pretty much the same for both Vellore and Chennai campus. There are slightly earlier curfews for the time being in the Chennai campus and you are allowed to stay out longer in the Vellore campus. In either case, there is a significant amount of restrictions imposed on students regardless of the campus vellore or chennai.')
            if get_message_text(update) == "I want know more about Size of campus" or get_message_text(update) == "Size of campus":
                send_message(get_chat_id(update), 'the Vellore campus is much larger in size. The Chennai campus is also fairly large and I have seen it develop tremendously during my 3 years here.')
            if get_message_text(update) == "What are the minimum marks required in VITEEE to get CSE at VIT Vellore?" or get_message_text(update) == "minimum marks required":
                send_message(get_chat_id(update), 'No cutoff for admission, all based upon ranks. Every year the strength increases. 2014-18 batch(my batch) had 240 seats in the following distribution of categories:100 seats category 1,50 seats category 2,50 seats category 3,40 seats category 4')
            if get_message_text(update) == "What is the maximum and average package given at VIT for CSE?" or get_message_text(update) == "maximum and average package":
                send_message(get_chat_id(update), 'Super Dream offers:Myntra,Snap deal,Google,Microsoft,Amazon,Paypal,Code Nation (Very rare but package close t0 20 lpa),Some of the highest packages offered at super dream offers go beyond 15 lakhs per annum. Snap deal and Myntra have offered packages of 15 lakhs per annum. Google has visited VIT a few times well not physically, in 2013 they offered an online test and screened out everyone except 2 guys.')
            if get_message_text(update) == "What is the minimum rank to get admission into VIT?" or get_message_text(update) == "minimum rank to get admission":
                send_message(get_chat_id(update), 'The merit seats for CSE get filled by around 5k rank and that of IT by around 8k. The seats other than merit list consists of 3 categories. Category 1 consists of merit list. In the year 2015, there were around 60% seats based on merit list.After the merit list, comes category 2, where your annual fees increases by around 1lac. For category 3, 4 and 5, fee increases by 2 lac, 3 lac and 4 lac respectively.')
            if get_message_text(update) == "xShould I go for VIT Bhopal?" or get_message_text(update) == "Bhopal":
                send_message(get_chat_id(update), 'The answer by all courses, faculty, campuses and students.Y.E.S. Now for the matter of fact you must ask for reasons.')
            if get_message_text(update) == "How is the IT branch in VIT Vellore?" or get_message_text(update) == "IT branch":
                send_message(get_chat_id(update), 'It is good to get one.')
            if get_message_text(update) == "Quit" or get_message_text(update) == "Thankyou":
                send_message(get_chat_id(update), 'Bye for now. See you soon :) ","It was nice talking to you. See you soon :)')
            if get_message_text(update) == "(hi|hey|hello|hola|holla)(.*)" or get_message_text(update) == "Heya":
                send_message(get_chat_id(update), 'Hello", "Hey there')
            else:
              send_message(get_chat_id(update), "anything else you want to know?")
              update_id += 1

          


main()